name: timetap
description: "App to clock in quickly and easily"
publish_to: 'Hyron'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  english_words: ^4.0.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/svg/appLogo.svg
  uses-material-design: true
