name: timetap
description: "App to clock in quickly and easily"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.3
  provider: ^6.0.5
  english_words: ^4.0.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.5
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
    - lib/l10n/backend/
    - lib/l10n/countries/
