name: timetap
description: "App to clock in quickly and easily"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.3
  provider: ^6.0.5
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.5
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  http: ^0.13.4
  http_interceptor: ^1.0.1
  nfc_manager: ^3.4.0
  local_auth: ^2.1.3
  geolocator: ^12.0.0
  collection: ^1.18.0
  shimmer: ^2.0.0
  geocoding: ^2.0.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/
